spring:
  # Test Database Configuration (H2 in-memory)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5

  # Test JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false

  # Test Cache Configuration
  cache:
    type: simple

  # Test Redis Configuration (Embedded)
  data:
    redis:
      host: localhost
      port: 6370

  # Test Kafka Configuration (Embedded)
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    consumer:
      group-id: test-group
    producer:
      retries: 0

  # Test Flyway Configuration
  flyway:
    enabled: false

# Test Server Configuration
server:
  port: 0  # Random port for tests

# Test Logging
logging:
  level:
    com.bisttrading: DEBUG
    org.springframework.test: DEBUG
    org.testcontainers: INFO
    org.springframework.kafka.test: DEBUG

# Test Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Test Security Configuration
security:
  jwt:
    secret: test-secret-key-for-testing-only
    expiration: 60000  # 1 minute for tests

# Test OpenAPI
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Test Feature Flags
app:
  features:
    real-time-trading: false
    advanced-analytics: false
    debug-mode: true