{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bist-trading-platform.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    {{- include "bist-trading-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: backend
    {{- include "bist-trading-platform.selectorLabels" . | nindent 4 }}
---
{{- if .Values.backend.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bist-trading-platform.fullname" . }}-backend-lb
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    {{- include "bist-trading-platform.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.backend.loadBalancer.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: backend
    {{- include "bist-trading-platform.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
